import React from "react";

function Head() {
  return (
    <>
      <title>İbrahim Akgün | Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}

export default Head;